package pl.com.sidorczuk.developers;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Maciej' at '23.09.17 15:47' with Gradle 2.14.1
 *
 * @author Maciej, @date 23.09.17 15:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
